# Generated by Django 4.1.7 on 2023-05-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='zip',
            new_name='zipcode',
        ),
    ]
